# Generated by Django 5.2.4 on 2025-08-03 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('name', models.CharField(max_length=200, null=True)),
                ('floor', models.CharField(max_length=200, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('s1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_s1', to='accounts.student')),
                ('s2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_s2', to='accounts.student')),
                ('s3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_s3', to='accounts.student')),
                ('s4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_s4', to='accounts.student')),
                ('s5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_s5', to='accounts.student')),
                ('s6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_s6', to='accounts.student')),
            ],
        ),
    ]
