version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: hostel_postgres
    restart: always
    environment:
      POSTGRES_DB: hmsdb
      POSTGRES_USER: aakash
      POSTGRES_PASSWORD: okay
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django-server:
    build: ./django-server
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django-server:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: hmsdb
      POSTGRES_USER: aakash
      POSTGRES_PASSWORD: okay
      POSTGRES_HOST: postgres

  node-server:
    build: ./node-server
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./node-server:/app
    environment:
      MONGO_URI: mongodb://host.docker.internal:27017/hmsdb  # if you're using MongoDB

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "5173:5173"  # or 3000 depending on your frontend dev server
    depends_on:
      - django-server
      - node-server
    volumes:
      - ./frontend:/app
    command: npm run dev  # change if needed
    environment:
      VITE_API_BASE_URL: http://localhost:5000
      VITE_DJANGO_URL: http://localhost:8000

volumes:
  postgres_data:
