# Generated by Django 5.2.4 on 2025-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mongoID',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
